### ISSUE TITLE
Auth header not set on login function

### ISSUE THREAD

**Issue by dothem1337** [chancezeus/angular-laravel-echo#8]
When you use only the "login" function from the EchoService, the header is not present in the "Request Headers". If I add the "auth: { headers: .... }" in the config, it will be present. But this is not the usecase, because you want set this in the configs. Also if I define it in the config, it will be performed twice.

Anyone can help me? Thanks!

**Comment by appelit-user** [comment]
Please provide a bit more detail about your setup, for example are you using pusher or socket.io, why do you assume the headers are not set and what method did you use to determine this?

The auth headers should be replaced with the headers provided (as can be seen here: https://github.com/chancezeus/angular-laravel-echo/blob/master/src/lib/src/services/lib.service.ts#L688), however things might have changed in the "laravel-echo" package this package relies on that breaks this functionality...

Keep in mind that (once/if websocket connection is established) the headers will not be sent over a http connection but through the websocket connection instead, so you might just be looking in the wrong place...

**Comment by dothem1337** [comment]
I'm using the pusher client yes, but with this package https://github.com/beyondcode/laravel-websockets.

When I debug, I see, that the headers are replaced, thats correct. Then the call for the auth is made, and there is the header missing, which resolves to "Unauthenticated". By the way, I check this in chrome, where the calls are made.

Thats a good point. The connection to websocket server is etablished, then the auth call is happen. I'll try to investigate it, which headers are sent. But the auth method is not a websocket call, its a normal POST request to my api (laravel).

**Comment by chancezeus** [comment]
Just to make sure you understand how Laravel Echo works (independent of connector):
1. Laravel Echo makes connection to socket.io/pusher server (no auth info is exchanged directly)
2. Depending on available methods in browser and network config, the connection is upgraded to websocket or reverts to long polling (still no auth info)
3. When connecting to a channel the auth info is attached to the specific request (either as a header in case of long polling or as a part of the websocket payload)
4. Upon receipt, the socket.io/pusher server connects to laravel en requests authentication for the specified channel using the specified header(s) (so actual request NEVER comes from browser, but from the websocket server itself)
5. Laravel checks auth info (using the config info in routes/broadcast.php or other variants) and either grants or denies the user access based on response, this is sent back to the socket.io/pusher server
6. Depending on the previous, the socket.io/pusher server completes or denies the join to the specified channel

There is a bit more happening, but this is a general how it should work, so the only point in the flow where you might encounter the set headers is either INSIDE the packages sent over the websocket OR as headers on the "join" http requests (in case of long-polling). I myself use the package with laravel-echo-server mostly and never encountered any problems where auth headers are not sent properly (and I never supply any credentials before calling login method), however my experience with pusher is limited and it might be that either laravel-echo or pusher-js client have changed part of their methodology resulting in the login hack (because that is what it is, since laravel-echo actually does not (or at least did not) have a proper way to update auth headers without page refresh) being broken.

Please confirm that in your case headers are NOT sent as part of the join request inside the connected websocket, because that means something is/got broken when using pusher and I'll have to investigate, otherwise it is more likely that you accidentally are using web (cookie based) authentication or csrf verification on the broadcast auth endpoint instead of for example a JWT token in an authorization header.

**Comment by chancezeus** [comment]
Did some digging into pusher-js sources and indeed found the culprit. Pusher makes a (possibly deep) copy of the config data, I suggest trying it by supplying an empty "auth" config object, since if it is just a shallow copy that should be enough for the current implemenation to work. In the meantime I'll look into an update that is able to work without the having to provide the "auth" config object.

Can you let me know if it works (otherwise I'll have to dig deeper)

**Comment by dothem1337** [comment]
I already tried with an empty auth config, and it doesn't work. 

Which version of pusher-js did you use? Maybe I can switch back in the meanwhile to an older source.

**Comment by chancezeus** [comment]
I have made a few changes, can attached is a zip containing a tarball of the module. Can you confirm if it is working (or not) so I can release a new version to npm?

[package.zip](https://github.com/chancezeus/angular-laravel-echo/files/2669661/package.zip)

**Comment by dothem1337** [comment]
Works like a charm! Thank you for the fast fix.

As I see you updated also to the latest pusher-js, laravel-echo. Perfect!
